name: benchmark

on:
  workflow_dispatch:
    inputs:
      run_benchmark:
        description: 'Run benchmark tests (yes/no)'
        required: true
        default: 'no'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_benchmark == 'yes' }}
    steps:
      - name: Run Benchmark Tests
        run: |
          cd kzg_prover
          cargo bench
