name: Benchmark

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]  
  workflow_dispatch:
    inputs:
      run_benchmark:
        description: 'Run benchmark tests (yes/no)'
        required: true
        default: 'no'

jobs:
  benchmark:
    runs-on: [summa-solvency-bench-runner]
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_benchmark == 'yes' }}
    steps:
      - uses: actions/checkout@v3

      - name: Run Benchmark Tests
        run: |
          cd kzg_prover
          cargo bench

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: kzg_prover/target/criterion
